export enum Location {
  SEOUL = 'Seoul',
  BUSAN = 'Busan',
  DAEGU = 'Daegu',
  INCHEON = 'Incheon',
  GWANGJU = 'Gwangju',
  DAEJEON = 'Daejeon',
  ULSAN = 'Ulsan',
  SEJONG = 'Sejong',
  GYEONGGI = 'Gyeonggi',
  GANGWON = 'Gangwon',
  CHUNGBUK = 'Chungcheongbuk-do',
  CHUNGNAM = 'Chungcheongnam-do',
  JEONBUK = 'Jeollabuk-do',
  JEONNAM = 'Jeollanam-do',
  GYEONGBUK = 'Gyeongsangbuk-do',
  GYEONGNAM = 'Gyeongsangnam-do',
  JEJU = 'Jeju',
}
